INSERT INTO Suppliers (Name) VALUES ('Abex');
INSERT INTO Suppliers (Name) VALUES ('Adept');
INSERT INTO Suppliers (Name) VALUES ('Alan Brookes');
INSERT INTO Suppliers (Name) VALUES ('Expert');
INSERT INTO Suppliers (Name) VALUES ('Fulton');
INSERT INTO Suppliers (Name) VALUES ('Gilby');
INSERT INTO Suppliers (Name) VALUES ('Howarth Timber');
INSERT INTO Suppliers (Name) VALUES ('Quest');
INSERT INTO Suppliers (Name) VALUES ('TC Direct');
INSERT INTO Suppliers (Name) VALUES ('Wenglor');