INSERT INTO Risks (RiskName, Description, MaintRequestType) VALUES ('Slips, trips and falls', '', 'Both');
INSERT INTO Risks (RiskName, Description, MaintRequestType) VALUES ('Falls from height', '', 'Both');
INSERT INTO Risks (RiskName, Description, MaintRequestType) VALUES ('Contact with moving machinery', '', 'Both');
INSERT INTO Risks (RiskName, Description, MaintRequestType) VALUES ('Electrical', '', 'Both');
INSERT INTO Risks (RiskName, Description, MaintRequestType) VALUES ('Hazardous substances', '', 'Both');
INSERT INTO Risks (RiskName, Description, MaintRequestType) VALUES ('Fire explosion', '', 'Both');
INSERT INTO Risks (RiskName, Description, MaintRequestType) VALUES ('Plant - equipment damage', '', 'Both');
INSERT INTO Risks (RiskName, Description, MaintRequestType) VALUES ('Manual handling', '', 'Both');
INSERT INTO Risks (RiskName, Description, MaintRequestType) VALUES ('Hit by falling objects', '', 'Both');
INSERT INTO Risks (RiskName, Description, MaintRequestType) VALUES ('Cut on shape edges', '', 'Both');
INSERT INTO Risks (RiskName, Description, MaintRequestType) VALUES ('Crush injuires', '', 'Both');
INSERT INTO Risks (RiskName, Description, MaintRequestType) VALUES ('Niose and vibration', '', 'Both');
INSERT INTO Risks (RiskName, Description, MaintRequestType) VALUES ('Burns (hot & cold', '', 'Both');
INSERT INTO Risks (RiskName, Description, MaintRequestType) VALUES ('Enviornmental impact', '', 'Both');